
spring:
  application:
    name: mtp-app

  profiles:
    active: dev             # until another profile is necessary

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}


# actuator config
  # for now, should restrict later
management:
  endpoints:
    web:
      exposure:
        include: '*'

# URLs
mtp:
  watchlist-svc:
    base-url: http://localhost:8081
  profile-svc:
    base-url: http://localhost:8082
  quote-svc:
    base-url: http://localhost:8083
