
spring:
  application:
    name: mtp-app

  profiles:
    active: dev             # until another profile is necessary

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ce78b7d31c46a70a11f0
            clientSecret: cfed7cd48f43b7eef576d51220aa12f329a83aba
          google:
            clientId: 812283781790-0lcqbque914v6p545gjfi0cg4aqg5cfu.apps.googleusercontent.com
            clientSecret: rdT5RMfB3JxtONoRmwI1cMKZ


# actuator config
  # for now, should restrict later
management:
  endpoints:
    web:
      exposure:
        include: '*'

# URLs
mtp:
  watchlist-svc:
    base-url: http://localhost:8081
  profile-svc:
    base-url: http://localhost:8082
  quote-svc:
    base-url: http://localhost:8083
